insert into musico (id, nombre, apellidos, username, password, tipo_instrumento, fecha_alta, admin) values (1, 'Alvaro', 'Castilla Cano', 'alvarocastilla@amueci.es', '{bcrypt}$2y$10$ddfFumDiAoDhpNj0XYRVHe3CEazScrvDNLqU2X8VwXGCoS6HT4Dt6', 'Percusion', '2020-01-06', false);
insert into musico (id, nombre, apellidos, username, password, tipo_instrumento, fecha_alta, admin) values (2, 'Lucas', 'Falla Urtiaga', 'lucasfalla@amueci.es', '{bcrypt}$2y$10$ddfFumDiAoDhpNj0XYRVHe3CEazScrvDNLqU2X8VwXGCoS6HT4Dt6', 'Percusion', '2019-05-01', false);
insert into musico (id, nombre, apellidos, username, password, tipo_instrumento, fecha_alta, admin) values (3, 'admin', 'admin', 'admin', '{bcrypt}$2y$10$Ra8hLpI7cMY21iuUhxI0e.SMoSgjtpABaEEdw9gVu2R1MuLLweFbe', null, '2019-05-01', true);
insert into musico (id, nombre, apellidos, username, password, tipo_instrumento, fecha_alta, admin) values (4, 'Ana', 'Martín Sánchez', 'anamartin@amueci.es', '{bcrypt}$2y$10$ddfFumDiAoDhpNj0XYRVHe3CEazScrvDNLqU2X8VwXGCoS6HT4Dt6', 'VientoMadera', '2017-06-23', false);
insert into musico (id, nombre, apellidos, username, password, tipo_instrumento, fecha_alta, admin) values (5, 'Luis', 'Gómez Pérez', 'luisgomez@amueci.es', '{bcrypt}$2y$10$ddfFumDiAoDhpNj0XYRVHe3CEazScrvDNLqU2X8VwXGCoS6HT4Dt6', 'Percusion', '2019-09-12', false);
insert into musico (id, nombre, apellidos, username, password, tipo_instrumento, fecha_alta, admin) values (6, 'Marta', 'Hernández Díaz', 'martahernandez@amueci.es', '{bcrypt}$2y$10$ddfFumDiAoDhpNj0XYRVHe3CEazScrvDNLqU2X8VwXGCoS6HT4Dt6', 'VientoMetal', '2020-11-08', false);
insert into musico (id, nombre, apellidos, username, password, tipo_instrumento, fecha_alta, admin) values (7, 'Carlos', 'Jiménez García', 'carlosjimenez@amueci.es', '{bcrypt}$2y$10$ddfFumDiAoDhpNj0XYRVHe3CEazScrvDNLqU2X8VwXGCoS6HT4Dt6', 'VientoMadera', '2018-04-17', false);
insert into musico (id, nombre, apellidos, username, password, tipo_instrumento, fecha_alta, admin) values (8, 'Lucía', 'Moreno Ruiz', 'luciamoreno@amueci.es', '{bcrypt}$2y$10$ddfFumDiAoDhpNj0XYRVHe3CEazScrvDNLqU2X8VwXGCoS6HT4Dt6', 'Percusion', '2019-12-20', false);
insert into musico (id, nombre, apellidos, username, password, tipo_instrumento, fecha_alta, admin) values (9, 'Jorge', 'Fernández Gil', 'jorgefernandez@amueci.es', '{bcrypt}$2y$10$ddfFumDiAoDhpNj0XYRVHe3CEazScrvDNLqU2X8VwXGCoS6HT4Dt6', 'VientoMetal', '2017-08-31', false);
insert into musico (id, nombre, apellidos, username, password, tipo_instrumento, fecha_alta, admin) values (10, 'Elena', 'Sanz Ortiz', 'elenasanz@amueci.es', '{bcrypt}$2y$10$ddfFumDiAoDhpNj0XYRVHe3CEazScrvDNLqU2X8VwXGCoS6HT4Dt6', 'VientoMadera', '2020-02-22', false);
insert into musico (id, nombre, apellidos, username, password, tipo_instrumento, fecha_alta, admin) values (11, 'Javier', 'Martinez Lopez', 'javiermartinez@amueci.es', '{bcrypt}$2y$10$ddfFumDiAoDhpNj0XYRVHe3CEazScrvDNLqU2X8VwXGCoS6HT4Dt6', 'Percusion', '2022-01-10', false);
insert into musico (id, nombre, apellidos, username, password, tipo_instrumento, fecha_alta, admin) values (12, 'Ana', 'Gonzalez Ruiz', 'anagonzalez@amueci.es', '{bcrypt}$2y$10$ddfFumDiAoDhpNj0XYRVHe3CEazScrvDNLqU2X8VwXGCoS6HT4Dt6', 'VientoMetal', '2022-01-10', false);
insert into musico (id, nombre, apellidos, username, password, tipo_instrumento, fecha_alta, admin) values (13, 'Luis', 'Fernandez Gomez', 'luisfernandez@amueci.es', '{bcrypt}$2y$10$ddfFumDiAoDhpNj0XYRVHe3CEazScrvDNLqU2X8VwXGCoS6HT4Dt6', 'VientoMadera', '2022-01-10', false);
insert into musico (id, nombre, apellidos, username, password, tipo_instrumento, fecha_alta, admin) values (14, 'Elena', 'Garcia Sanchez', 'elenagarcia@amueci.es', '{bcrypt}$2y$10$ddfFumDiAoDhpNj0XYRVHe3CEazScrvDNLqU2X8VwXGCoS6HT4Dt6', 'Percusion', '2022-01-10', false),
insert into musico (id, nombre, apellidos, username, password, tipo_instrumento, fecha_alta, admin) values (15, 'Manuel', 'Rodriguez Diaz', 'manuelrodriguez@amueci.es', '{bcrypt}$2y$10$ddfFumDiAoDhpNj0XYRVHe3CEazScrvDNLqU2X8VwXGCoS6HT4Dt6', 'VientoMetal', '2022-01-10', false);
insert into musico (id, nombre, apellidos, username, password, tipo_instrumento, fecha_alta, admin) values (16, 'Carmen', 'Lopez Martinez', 'carmenlopez@amueci.es', '{bcrypt}$2y$10$ddfFumDiAoDhpNj0XYRVHe3CEazScrvDNLqU2X8VwXGCoS6HT4Dt6', 'VientoMadera', '2022-01-10', false);
insert into musico (id, nombre, apellidos, username, password, tipo_instrumento, fecha_alta, admin) values (17, 'Miguel', 'Perez Gomez', 'miguelperez@amueci.es', '{bcrypt}$2y$10$ddfFumDiAoDhpNj0XYRVHe3CEazScrvDNLqU2X8VwXGCoS6HT4Dt6', 'Percusion', '2022-01-10', false);
insert into musico (id, nombre, apellidos, username, password, tipo_instrumento, fecha_alta, admin) values (18, 'Lucia', 'Hernandez Lopez', 'luciahernandez@amueci.es', '{bcrypt}$2y$10$ddfFumDiAoDhpNj0XYRVHe3CEazScrvDNLqU2X8VwXGCoS6HT4Dt6', 'VientoMetal', '2022-01-10', false);
insert into musico (id, nombre, apellidos, username, password, tipo_instrumento, fecha_alta, admin) values (19, 'Pedro', 'Gomez Ruiz', 'pedrogomez@amueci.es', '{bcrypt}$2y$10$ddfFumDiAoDhpNj0XYRVHe3CEazScrvDNLqU2X8VwXGCoS6HT4Dt6', 'VientoMadera', '2022-01-10', false);
insert into musico (id, nombre, apellidos, username, password, tipo_instrumento, fecha_alta, admin) values (20, 'Laura', 'Martinez Sanchez', 'lauramartinez@amueci.es', '{bcrypt}$2y$10$ddfFumDiAoDhpNj0XYRVHe3CEazScrvDNLqU2X8VwXGCoS6HT4Dt6', 'Percusion', '2022-01-10', false);
insert into musico (id, nombre, apellidos, username, password, tipo_instrumento, fecha_alta, admin) values (21, 'Alberto', 'Lopez Fernandez', 'albertolopez@amueci.es', '{bcrypt}$2y$10$ddfFumDiAoDhpNj0XYRVHe3CEazScrvDNLqU2X8VwXGCoS6HT4Dt6', 'VientoMetal', '2022-01-10', false);
insert into musico (id, nombre, apellidos, username, password, tipo_instrumento, fecha_alta, admin) values (22, 'Sandra', 'Rodriguez Perez', 'sandrarodriguez@amueci.es', '{bcrypt}$2y$10$ddfFumDiAoDhpNj0XYRVHe3CEazScrvDNLqU2X8VwXGCoS6HT4Dt6', 'VientoMadera', '2022-01-10', false);
insert into musico (id, nombre, apellidos, username, password, tipo_instrumento, fecha_alta, admin) values (23, 'Jose', 'Garcia Martinez', 'josegarcia@amueci.es', '{bcrypt}$2y$10$ddfFumDiAoDhpNj0XYRVHe3CEazScrvDNLqU2X8VwXGCoS6HT4Dt6', 'Percusion', '2022-01-10', false);
insert into musico (id, nombre, apellidos, username, password, tipo_instrumento, fecha_alta, admin) values (24, 'Patricia', 'Gonzalez Hernandez', 'patriciagonzalez@amueci.es', '{bcrypt}$2y$10$ddfFumDiAoDhpNj0XYRVHe3CEazScrvDNLqU2X8VwXGCoS6HT4Dt6', 'VientoMetal', '2022-01-10', false);
insert into musico (id, nombre, apellidos, username, password, tipo_instrumento, fecha_alta, admin) values (25, 'Raul', 'Fernandez Garcia', 'raulfernandez@amueci.es', '{bcrypt}$2y$10$ddfFumDiAoDhpNj0XYRVHe3CEazScrvDNLqU2X8VwXGCoS6HT4Dt6', 'VientoMadera', '2022-01-10', false);
insert into musico (id, nombre, apellidos, username, password, tipo_instrumento, fecha_alta, admin) values (26, 'Beatriz', 'Hernandez Martinez', 'beatrizhernandez@amueci.es', '{bcrypt}$2y$10$ddfFumDiAoDhpNj0XYRVHe3CEazScrvDNLqU2X8VwXGCoS6HT4Dt6', 'Percusion', '2022-01-10', false);
insert into musico (id, nombre, apellidos, username, password, tipo_instrumento, fecha_alta, admin) values (27, 'Antonio', 'Perez Rodriguez', 'antonioperez@amueci.es', '{bcrypt}$2y$10$ddfFumDiAoDhpNj0XYRVHe3CEazScrvDNLqU2X8VwXGCoS6HT4Dt6', 'VientoMetal', '2022-01-10', false);
insert into musico (id, nombre, apellidos, username, password, tipo_instrumento, fecha_alta, admin) values (28, 'Sara', 'Gomez Ruiz', 'saragomez@amueci.es', '{bcrypt}$2y$10$ddfFumDiAoDhpNj0XYRVHe3CEazScrvDNLqU2X8VwXGCoS6HT4Dt6', 'VientoMadera', '2022-01-10', false);
insert into musico (id, nombre, apellidos, username, password, tipo_instrumento, fecha_alta, admin) values (29, 'Fernando', 'Ramirez Soto', 'fernandoramirez@amueci.es', '{bcrypt}$2y$10$ddfFumDiAoDhpNj0XYRVHe3CEazScrvDNLqU2X8VwXGCoS6HT4Dt6', 'Percusion', '2022-01-10', false);
insert into musico (id, nombre, apellidos, username, password, tipo_instrumento, fecha_alta, admin) values (30, 'Isabel', 'Jimenez Garcia', 'isabeljimenez@amueci.es', '{bcrypt}$2y$10$ddfFumDiAoDhpNj0XYRVHe3CEazScrvDNLqU2X8VwXGCoS6HT4Dt6', 'VientoMetal', '2022-01-10', false);
insert into musico (id, nombre, apellidos, username, password, tipo_instrumento, fecha_alta, admin) values (31, 'Pablo', 'Martinez Fernandez', 'pablomartinez@amueci.es', '{bcrypt}$2y$10$ddfFumDiAoDhpNj0XYRVHe3CEazScrvDNLqU2X8VwXGCoS6HT4Dt6', 'VientoMadera', '2022-01-10', false);
insert into musico (id, nombre, apellidos, username, password, tipo_instrumento, fecha_alta, admin) values (32, 'Sofia', 'Lopez Ruiz', 'sofialopez@amueci.es', '{bcrypt}$2y$10$ddfFumDiAoDhpNj0XYRVHe3CEazScrvDNLqU2X8VwXGCoS6HT4Dt6', 'Percusion', '2022-01-10', false);
insert into musico (id, nombre, apellidos, username, password, tipo_instrumento, fecha_alta, admin) values (33, 'Rafael', 'Gonzalez Perez', 'rafaelgonzalez@amueci.es', '{bcrypt}$2y$10$ddfFumDiAoDhpNj0XYRVHe3CEazScrvDNLqU2X8VwXGCoS6HT4Dt6', 'VientoMetal', '2022-01-10', false);
insert into musico (id, nombre, apellidos, username, password, tipo_instrumento, fecha_alta, admin) values (34, 'Marta', 'Garcia Sanchez', 'martagarcia@amueci.es', '{bcrypt}$2y$10$ddfFumDiAoDhpNj0XYRVHe3CEazScrvDNLqU2X8VwXGCoS6HT4Dt6', 'VientoMadera', '2022-01-10', false);
insert into musico (id, nombre, apellidos, username, password, tipo_instrumento, fecha_alta, admin) values (35, 'Jorge', 'Rodriguez Ramirez', 'jorgerodriguez@amueci.es', '{bcrypt}$2y$10$ddfFumDiAoDhpNj0XYRVHe3CEazScrvDNLqU2X8VwXGCoS6HT4Dt6', 'Percusion', '2022-01-10', false);
insert into musico (id, nombre, apellidos, username, password, tipo_instrumento, fecha_alta, admin) values (36, 'Cristina', 'Sanchez Jimenez', 'cristinasanchez@amueci.es', '{bcrypt}$2y$10$ddfFumDiAoDhpNj0XYRVHe3CEazScrvDNLqU2X8VwXGCoS6HT4Dt6', 'VientoMetal', '2022-01-10', false);
insert into musico (id, nombre, apellidos, username, password, tipo_instrumento, fecha_alta, admin) values (37, 'Victor', 'Perez Hernandez', 'victorperez@amueci.es', '{bcrypt}$2y$10$ddfFumDiAoDhpNj0XYRVHe3CEazScrvDNLqU2X8VwXGCoS6HT4Dt6', 'VientoMadera', '2022-01-10', false);
insert into musico (id, nombre, apellidos, username, password, tipo_instrumento, fecha_alta, admin) values (38, 'Alba', 'Ruiz Garcia', 'albaruiz@amueci.es', '{bcrypt}$2y$10$ddfFumDiAoDhpNj0XYRVHe3CEazScrvDNLqU2X8VwXGCoS6HT4Dt6', 'Percusion', '2022-01-10', false);
insert into musico (id, nombre, apellidos, username, password, tipo_instrumento, fecha_alta, admin) values (39, 'Roberto', 'Fernandez Lopez', 'robertofernandez@amueci.es', '{bcrypt}$2y$10$ddfFumDiAoDhpNj0XYRVHe3CEazScrvDNLqU2X8VwXGCoS6HT4Dt6', 'VientoMetal', '2022-01-10', false);
insert into musico (id, nombre, apellidos, username, password, tipo_instrumento, fecha_alta, admin) values (40, 'Teresa', 'Diaz Martinez', 'teresadiaz@amueci.es', '{bcrypt}$2y$10$ddfFumDiAoDhpNj0XYRVHe3CEazScrvDNLqU2X8VwXGCoS6HT4Dt6', 'VientoMadera', '2022-01-10', false);
insert into musico (id, nombre, apellidos, username, password, tipo_instrumento, fecha_alta, admin) values (41, 'Antonio', 'Gomez Ruiz', 'antoniogomez@amueci.es', '{bcrypt}$2y$10$ddfFumDiAoDhpNj0XYRVHe3CEazScrvDNLqU2X8VwXGCoS6HT4Dt6', 'Percusion', '2022-01-10', false);
insert into musico (id, nombre, apellidos, username, password, tipo_instrumento, fecha_alta, admin) values (42, 'Natalia', 'Hernandez Sanchez', 'nataliahernandez@amueci.es', '{bcrypt}$2y$10$ddfFumDiAoDhpNj0XYRVHe3CEazScrvDNLqU2X8VwXGCoS6HT4Dt6', 'VientoMetal', '2022-01-10', false);
insert into musico (id, nombre, apellidos, username, password, tipo_instrumento, fecha_alta, admin) values (43, 'Francisco', 'Lopez Fernandez', 'franciscolopez@amueci.es', '{bcrypt}$2y$10$ddfFumDiAoDhpNj0XYRVHe3CEazScrvDNLqU2X8VwXGCoS6HT4Dt6', 'VientoMadera', '2022-01-10', false);
insert into musico (id, nombre, apellidos, username, password, tipo_instrumento, fecha_alta, admin) values (44, 'Eva', 'Ramirez Martinez', 'evaramirez@amueci.es', '{bcrypt}$2y$10$ddfFumDiAoDhpNj0XYRVHe3CEazScrvDNLqU2X8VwXGCoS6HT4Dt6', 'Percusion', '2022-01-10', false);
insert into musico (id, nombre, apellidos, username, password, tipo_instrumento, fecha_alta, admin) values (45, 'Juan', 'Martinez Gonzalez', 'juanmartinez@amueci.es', '{bcrypt}$2y$10$ddfFumDiAoDhpNj0XYRVHe3CEazScrvDNLqU2X8VwXGCoS6HT4Dt6', 'VientoMetal', '2022-01-10', false);
insert into musico (id, nombre, apellidos, username, password, tipo_instrumento, fecha_alta, admin) values (46, 'Claudia', 'Fernandez Ruiz', 'claudiafernandez@amueci.es', '{bcrypt}$2y$10$ddfFumDiAoDhpNj0XYRVHe3CEazScrvDNLqU2X8VwXGCoS6HT4Dt6', 'VientoMadera', '2022-01-10', false);
insert into musico (id, nombre, apellidos, username, password, tipo_instrumento, fecha_alta, admin) values (47, 'Andres', 'Sanchez Ramirez', 'andressanchez@amueci.es', '{bcrypt}$2y$10$ddfFumDiAoDhpNj0XYRVHe3CEazScrvDNLqU2X8VwXGCoS6HT4Dt6', 'Percusion', '2022-01-10', false);
insert into musico (id, nombre, apellidos, username, password, tipo_instrumento, fecha_alta, admin) values (48, 'Silvia', 'Lopez Perez', 'silvialopez@amueci.es', '{bcrypt}$2y$10$ddfFumDiAoDhpNj0XYRVHe3CEazScrvDNLqU2X8VwXGCoS6HT4Dt6', 'VientoMetal', '2022-01-10', false);
insert into musico (id, nombre, apellidos, username, password, tipo_instrumento, fecha_alta, admin) values (49, 'Diego', 'Garcia Diaz', 'diegogarcia@amueci.es', '{bcrypt}$2y$10$ddfFumDiAoDhpNj0XYRVHe3CEazScrvDNLqU2X8VwXGCoS6HT4Dt6', 'VientoMadera', '2022-01-10', false);
insert into musico (id, nombre, apellidos, username, password, tipo_instrumento, fecha_alta, admin) values (50, 'Marcos', 'Rodríguez López', 'marcosrodriguez@amueci.es', '{bcrypt}$2y$10$ddfFumDiAoDhpNj0XYRVHe3CEazScrvDNLqU2X8VwXGCoS6HT4Dt6', 'VientoMetal', '2018-02-15', false);
insert into musico (id, nombre, apellidos, username, password, tipo_instrumento, fecha_alta, admin) values (51, 'Jorge', 'Martinez Diaz', 'jorgemartinez@amueci.es', '{bcrypt}$2y$10$ddfFumDiAoDhpNj0XYRVHe3CEazScrvDNLqU2X8VwXGCoS6HT4Dt6', 'Percusion', '2022-01-10', false);
insert into musico (id, nombre, apellidos, username, password, tipo_instrumento, fecha_alta, admin) values (52, 'Alicia', 'Gonzalez Fernandez', 'aliciagonzalez@amueci.es', '{bcrypt}$2y$10$ddfFumDiAoDhpNj0XYRVHe3CEazScrvDNLqU2X8VwXGCoS6HT4Dt6', 'VientoMetal', '2022-01-10', false);
insert into musico (id, nombre, apellidos, username, password, tipo_instrumento, fecha_alta, admin) values (53, 'Ricardo', 'Lopez Perez', 'ricardolopez@amueci.es', '{bcrypt}$2y$10$ddfFumDiAoDhpNj0XYRVHe3CEazScrvDNLqU2X8VwXGCoS6HT4Dt6', 'VientoMadera', '2022-01-10', false);
insert into musico (id, nombre, apellidos, username, password, tipo_instrumento, fecha_alta, admin) values (54, 'Teresa', 'Garcia Ruiz', 'teresagarcia@amueci.es', '{bcrypt}$2y$10$ddfFumDiAoDhpNj0XYRVHe3CEazScrvDNLqU2X8VwXGCoS6HT4Dt6', 'Percusion', '2022-01-10', false);
insert into musico (id, nombre, apellidos, username, password, tipo_instrumento, fecha_alta, admin) values (55, 'Fernando', 'Martinez Sanchez', 'fernandomartinez@amueci.es', '{bcrypt}$2y$10$ddfFumDiAoDhpNj0XYRVHe3CEazScrvDNLqU2X8VwXGCoS6HT4Dt6', 'VientoMetal', '2022-01-10', false);
insert into musico (id, nombre, apellidos, username, password, tipo_instrumento, fecha_alta, admin) values (56, 'Isabel', 'Hernandez Garcia', 'isabelhernandez@amueci.es', '{bcrypt}$2y$10$ddfFumDiAoDhpNj0XYRVHe3CEazScrvDNLqU2X8VwXGCoS6HT4Dt6', 'VientoMadera', '2022-01-10', false);
insert into musico (id, nombre, apellidos, username, password, tipo_instrumento, fecha_alta, admin) values (57, 'Sergio', 'Perez Martinez', 'sergioperez@amueci.es', '{bcrypt}$2y$10$ddfFumDiAoDhpNj0XYRVHe3CEazScrvDNLqU2X8VwXGCoS6HT4Dt6', 'Percusion', '2022-01-10', false);
insert into musico (id, nombre, apellidos, username, password, tipo_instrumento, fecha_alta, admin) values (58, 'Natalia', 'Lopez Sanchez', 'natalialopez@amueci.es', '{bcrypt}$2y$10$ddfFumDiAoDhpNj0XYRVHe3CEazScrvDNLqU2X8VwXGCoS6HT4Dt6', 'VientoMetal', '2022-01-10', false);
insert into musico (id, nombre, apellidos, username, password, tipo_instrumento, fecha_alta, admin) values (59, 'Andres', 'Gomez Hernandez', 'andresgomez@amueci.es', '{bcrypt}$2y$10$ddfFumDiAoDhpNj0XYRVHe3CEazScrvDNLqU2X8VwXGCoS6HT4Dt6', 'VientoMadera', '2022-01-10', false);
insert into musico (id, nombre, apellidos, username, password, tipo_instrumento, fecha_alta, admin) values (60, 'Raquel', 'Martinez Ruiz', 'raquelmartinez@amueci.es', '{bcrypt}$2y$10$ddfFumDiAoDhpNj0XYRVHe3CEazScrvDNLqU2X8VwXGCoS6HT4Dt6', 'Percusion', '2022-01-10', false);
insert into musico (id, nombre, apellidos, username, password, tipo_instrumento, fecha_alta, admin) values (61, 'Eduardo', 'Hernandez Gomez', 'eduardohernandez@amueci.es', '{bcrypt}$2y$10$ddfFumDiAoDhpNj0XYRVHe3CEazScrvDNLqU2X8VwXGCoS6HT4Dt6', 'VientoMetal', '2022-01-10', false);
insert into musico (id, nombre, apellidos, username, password, tipo_instrumento, fecha_alta, admin) values (62, 'Lorena', 'Garcia Fernandez', 'lorenagarcia@amueci.es', '{bcrypt}$2y$10$ddfFumDiAoDhpNj0XYRVHe3CEazScrvDNLqU2X8VwXGCoS6HT4Dt6', 'VientoMadera', '2022-01-10', false);
insert into musico (id, nombre, apellidos, username, password, tipo_instrumento, fecha_alta, admin) values (63, 'Diego', 'Rodriguez Lopez', 'diegorodriguez@amueci.es', '{bcrypt}$2y$10$ddfFumDiAoDhpNj0XYRVHe3CEazScrvDNLqU2X8VwXGCoS6HT4Dt6', 'Percusion', '2022-01-10', false);
insert into musico (id, nombre, apellidos, username, password, tipo_instrumento, fecha_alta, admin) values (64, 'Cristina', 'Martinez Gonzalez', 'cristinagarcia@amueci.es', '{bcrypt}$2y$10$ddfFumDiAoDhpNj0XYRVHe3CEazScrvDNLqU2X8VwXGCoS6HT4Dt6', 'VientoMetal', '2022-01-10', false);
insert into musico (id, nombre, apellidos, username, password, tipo_instrumento, fecha_alta, admin) values (65, 'Jose', 'Fernandez Martinez', 'josefernandez@amueci.es', '{bcrypt}$2y$10$ddfFumDiAoDhpNj0XYRVHe3CEazScrvDNLqU2X8VwXGCoS6HT4Dt6', 'VientoMadera', '2022-01-10', false);
insert into musico (id, nombre, apellidos, username, password, tipo_instrumento, fecha_alta, admin) values (66, 'Paula', 'Lopez Gomez', 'paulalopez@amueci.es', '{bcrypt}$2y$10$ddfFumDiAoDhpNj0XYRVHe3CEazScrvDNLqU2X8VwXGCoS6HT4Dt6', 'Percusion', '2022-01-10', false);
insert into musico (id, nombre, apellidos, username, password, tipo_instrumento, fecha_alta, admin) values (67, 'Roberto', 'Garcia Sanchez', 'robertogarcia@amueci.es', '{bcrypt}$2y$10$ddfFumDiAoDhpNj0XYRVHe3CEazScrvDNLqU2X8VwXGCoS6HT4Dt6', 'VientoMetal', '2022-01-10', false);
insert into musico (id, nombre, apellidos, username, password, tipo_instrumento, fecha_alta, admin) values (68, 'Andrea', 'Martinez Hernandez', 'andreamartinez@amueci.es', '{bcrypt}$2y$10$ddfFumDiAoDhpNj0XYRVHe3CEazScrvDNLqU2X8VwXGCoS6HT4Dt6', 'VientoMadera', '2022-01-10', false);
insert into musico (id, nombre, apellidos, username, password, tipo_instrumento, fecha_alta, admin) values (69, 'Hugo', 'Gonzalez Perez', 'hugogonzalez@amueci.es', '{bcrypt}$2y$10$ddfFumDiAoDhpNj0XYRVHe3CEazScrvDNLqU2X8VwXGCoS6HT4Dt6', 'Percusion', '2022-01-10', false);
insert into musico (id, nombre, apellidos, username, password, tipo_instrumento, fecha_alta, admin) values (70, 'Monica', 'Lopez Ruiz', 'monicalopez@amueci.es', '{bcrypt}$2y$10$ddfFumDiAoDhpNj0XYRVHe3CEazScrvDNLqU2X8VwXGCoS6HT4Dt6', 'VientoMetal', '2022-01-10', false);
insert into musico (id, nombre, apellidos, username, password, tipo_instrumento, fecha_alta, admin) values (71, 'Javier', 'Fernandez Garcia', 'javierfernandez@amueci.es', '{bcrypt}$2y$10$ddfFumDiAoDhpNj0XYRVHe3CEazScrvDNLqU2X8VwXGCoS6HT4Dt6', 'VientoMadera', '2022-01-10', false);
insert into musico (id, nombre, apellidos, username, password, tipo_instrumento, fecha_alta, admin) values (72, 'Irene', 'Martinez Lopez', 'irenemartinez@amueci.es', '{bcrypt}$2y$10$ddfFumDiAoDhpNj0XYRVHe3CEazScrvDNLqU2X8VwXGCoS6HT4Dt6', 'Percusion', '2022-01-10', false);
insert into musico (id, nombre, apellidos, username, password, tipo_instrumento, fecha_alta, admin) values (73, 'Victor', 'Gomez Hernandez', 'victorgomez@amueci.es', '{bcrypt}$2y$10$ddfFumDiAoDhpNj0XYRVHe3CEazScrvDNLqU2X8VwXGCoS6HT4Dt6', 'VientoMetal', '2022-01-10', false);
insert into musico (id, nombre, apellidos, username, password, tipo_instrumento, fecha_alta, admin) values (74, 'David', 'Martinez Fernandez', 'davidmartinez@amueci.es', '{bcrypt}$2y$10$ddfFumDiAoDhpNj0XYRVHe3CEazScrvDNLqU2X8VwXGCoS6HT4Dt6', 'VientoMadera', '2022-01-10', false);
insert into musico (id, nombre, apellidos, username, password, tipo_instrumento, fecha_alta, admin) values (75, 'Elena', 'Gonzalez Ruiz', 'elenagonzalez@amueci.es', '{bcrypt}$2y$10$ddfFumDiAoDhpNj0XYRVHe3CEazScrvDNLqU2X8VwXGCoS6HT4Dt6', 'Percusion', '2022-01-10', false);
insert into musico (id, nombre, apellidos, username, password, tipo_instrumento, fecha_alta, admin) values (76, 'Carlos', 'Hernandez Perez', 'carloshernandez@amueci.es', '{bcrypt}$2y$10$ddfFumDiAoDhpNj0XYRVHe3CEazScrvDNLqU2X8VwXGCoS6HT4Dt6', 'VientoMetal', '2022-01-10', false);
insert into musico (id, nombre, apellidos, username, password, tipo_instrumento, fecha_alta, admin) values (77, 'Sara', 'Lopez Gomez', 'saralopez@amueci.es', '{bcrypt}$2y$10$ddfFumDiAoDhpNj0XYRVHe3CEazScrvDNLqU2X8VwXGCoS6HT4Dt6', 'VientoMadera', '2022-01-10', false);
insert into musico (id, nombre, apellidos, username, password, tipo_instrumento, fecha_alta, admin) values (78, 'Alejandro', 'Garcia Martinez', 'alejandrogarcia@amueci.es', '{bcrypt}$2y$10$ddfFumDiAoDhpNj0XYRVHe3CEazScrvDNLqU2X8VwXGCoS6HT4Dt6', 'Percusion', '2022-01-10', false);
insert into musico (id, nombre, apellidos, username, password, tipo_instrumento, fecha_alta, admin) values (79, 'Laura', 'Martinez Fernandez', 'lauramartinez@amueci.es', '{bcrypt}$2y$10$ddfFumDiAoDhpNj0XYRVHe3CEazScrvDNLqU2X8VwXGCoS6HT4Dt6', 'VientoMetal', '2022-01-10', false);
insert into musico (id, nombre, apellidos, username, password, tipo_instrumento, fecha_alta, admin) values (80, 'Pablo', 'Gonzalez Lopez', 'pablogonzalez@amueci.es', '{bcrypt}$2y$10$ddfFumDiAoDhpNj0XYRVHe3CEazScrvDNLqU2X8VwXGCoS6HT4Dt6', 'VientoMadera', '2022-01-10', false);
insert into musico (id, nombre, apellidos, username, password, tipo_instrumento, fecha_alta, admin) values (81, 'Maria', 'Fernandez Gomez', 'mariafernandez@amueci.es', '{bcrypt}$2y$10$ddfFumDiAoDhpNj0XYRVHe3CEazScrvDNLqU2X8VwXGCoS6HT4Dt6', 'Percusion', '2022-01-10', false);
insert into musico (id, nombre, apellidos, username, password, tipo_instrumento, fecha_alta, admin) values (82, 'Daniel', 'Hernandez Perez', 'danielhernandez@amueci.es', '{bcrypt}$2y$10$ddfFumDiAoDhpNj0XYRVHe3CEazScrvDNLqU2X8VwXGCoS6HT4Dt6', 'VientoMetal', '2022-01-10', false);
insert into musico (id, nombre, apellidos, username, password, tipo_instrumento, fecha_alta, admin) values (83, 'Ana', 'Lopez Gomez', 'analopez@amueci.es', '{bcrypt}$2y$10$ddfFumDiAoDhpNj0XYRVHe3CEazScrvDNLqU2X8VwXGCoS6HT4Dt6', 'VientoMadera', '2022-01-10', false);
insert into musico (id, nombre, apellidos, username, password, tipo_instrumento, fecha_alta, admin) values (84, 'Adrian', 'Garcia Martinez', 'adriangarcia@amueci.es', '{bcrypt}$2y$10$ddfFumDiAoDhpNj0XYRVHe3CEazScrvDNLqU2X8VwXGCoS6HT4Dt6', 'Percusion', '2022-01-10', false);
insert into musico (id, nombre, apellidos, username, password, tipo_instrumento, fecha_alta, admin) values (85, 'Sofia', 'Martinez Fernandez', 'sofiamartinez@amueci.es', '{bcrypt}$2y$10$ddfFumDiAoDhpNj0XYRVHe3CEazScrvDNLqU2X8VwXGCoS6HT4Dt6', 'VientoMetal', '2022-01-10', false);
insert into musico (id, nombre, apellidos, username, password, tipo_instrumento, fecha_alta, admin) values (86, 'Marcos', 'Gonzalez Lopez', 'marcosgonzalez@amueci.es', '{bcrypt}$2y$10$ddfFumDiAoDhpNj0XYRVHe3CEazScrvDNLqU2X8VwXGCoS6HT4Dt6', 'VientoMadera', '2022-01-10', false);
insert into musico (id, nombre, apellidos, username, password, tipo_instrumento, fecha_alta, admin) values (87, 'Celia', 'Fernandez Gomez', 'celiafernandez@amueci.es', '{bcrypt}$2y$10$ddfFumDiAoDhpNj0XYRVHe3CEazScrvDNLqU2X8VwXGCoS6HT4Dt6', 'Percusion', '2022-01-10', false);
insert into musico (id, nombre, apellidos, username, password, tipo_instrumento, fecha_alta, admin) values (88, 'Javier', 'Hernandez Perez', 'javierhernandez@amueci.es', '{bcrypt}$2y$10$ddfFumDiAoDhpNj0XYRVHe3CEazScrvDNLqU2X8VwXGCoS6HT4Dt6', 'VientoMetal', '2022-01-10', false);
insert into musico (id, nombre, apellidos, username, password, tipo_instrumento, fecha_alta, admin) values (89, 'Eva', 'Lopez Gomez', 'evalopez@amueci.es', '{bcrypt}$2y$10$ddfFumDiAoDhpNj0XYRVHe3CEazScrvDNLqU2X8VwXGCoS6HT4Dt6', 'VientoMadera', '2022-01-10', false);
insert into musico (id, nombre, apellidos, username, password, tipo_instrumento, fecha_alta, admin) values (90, 'Alejandro', 'Garcia Martinez', 'alejandrogarcia@amueci.es', '{bcrypt}$2y$10$ddfFumDiAoDhpNj0XYRVHe3CEazScrvDNLqU2X8VwXGCoS6HT4Dt6', 'Percusion', '2022-01-10', false);
insert into musico (id, nombre, apellidos, username, password, tipo_instrumento, fecha_alta, admin) values (91, 'Marina', 'Martinez Fernandez', 'marinamartinez@amueci.es', '{bcrypt}$2y$10$ddfFumDiAoDhpNj0XYRVHe3CEazScrvDNLqU2X8VwXGCoS6HT4Dt6', 'VientoMetal', '2022-01-10', false);
insert into musico (id, nombre, apellidos, username, password, tipo_instrumento, fecha_alta, admin) values (92, 'Lucas', 'Gonzalez Lopez', 'lucasgonzalez@amueci.es', '{bcrypt}$2y$10$ddfFumDiAoDhpNj0XYRVHe3CEazScrvDNLqU2X8VwXGCoS6HT4Dt6', 'VientoMadera', '2022-01-10', false);
insert into musico (id, nombre, apellidos, username, password, tipo_instrumento, fecha_alta, admin) values (93, 'Carla', 'Fernandez Gomez', 'carlafernandez@amueci.es', '{bcrypt}$2y$10$ddfFumDiAoDhpNj0XYRVHe3CEazScrvDNLqU2X8VwXGCoS6HT4Dt6', 'Percusion', '2022-01-10', false);
insert into musico (id, nombre, apellidos, username, password, tipo_instrumento, fecha_alta, admin) values (94, 'Sergio', 'Hernandez Perez', 'sergiohernandez@amueci.es', '{bcrypt}$2y$10$ddfFumDiAoDhpNj0XYRVHe3CEazScrvDNLqU2X8VwXGCoS6HT4Dt6', 'VientoMetal', '2022-01-10', false);
insert into musico (id, nombre, apellidos, username, password, tipo_instrumento, fecha_alta, admin) values (95, 'Marta', 'Lopez Gomez', 'martalopez@amueci.es', '{bcrypt}$2y$10$ddfFumDiAoDhpNj0XYRVHe3CEazScrvDNLqU2X8VwXGCoS6HT4Dt6', 'VientoMadera', '2022-01-10', false);
insert into musico (id, nombre, apellidos, username, password, tipo_instrumento, fecha_alta, admin) values (96, 'Alejandro', 'Garcia Martinez', 'alejandrogarcia@amueci.es', '{bcrypt}$2y$10$ddfFumDiAoDhpNj0XYRVHe3CEazScrvDNLqU2X8VwXGCoS6HT4Dt6', 'Percusion', '2022-01-10', false);
insert into musico (id, nombre, apellidos, username, password, tipo_instrumento, fecha_alta, admin) values (97, 'Elena', 'Martinez Fernandez', 'elenamartinez@amueci.es', '{bcrypt}$2y$10$ddfFumDiAoDhpNj0XYRVHe3CEazScrvDNLqU2X8VwXGCoS6HT4Dt6', 'VientoMetal', '2022-01-10', false);
insert into musico (id, nombre, apellidos, username, password, tipo_instrumento, fecha_alta, admin) values (98, 'Javier', 'Gonzalez Lopez', 'javiergonzalez@amueci.es', '{bcrypt}$2y$10$ddfFumDiAoDhpNj0XYRVHe3CEazScrvDNLqU2X8VwXGCoS6HT4Dt6', 'VientoMadera', '2022-01-10', false);
insert into musico (id, nombre, apellidos, username, password, tipo_instrumento, fecha_alta, admin) values (99, 'Lucia', 'Fernandez Gomez', 'luciafernandez@amueci.es', '{bcrypt}$2y$10$ddfFumDiAoDhpNj0XYRVHe3CEazScrvDNLqU2X8VwXGCoS6HT4Dt6', 'Percusion', '2022-01-10', false);
insert into musico (id, nombre, apellidos, username, password, tipo_instrumento, fecha_alta, admin) values (100, 'Diego', 'Hernandez Perez', 'diegohernandez@amueci.es', '{bcrypt}$2y$10$ddfFumDiAoDhpNj0XYRVHe3CEazScrvDNLqU2X8VwXGCoS6HT4Dt6', 'VientoMetal', '2022-01-10', false);
insert into musico (id, nombre, apellidos, username, password, tipo_instrumento, fecha_alta, admin) values (101, 'Sara', 'Lopez Gomez', 'saralopez@amueci.es', '{bcrypt}$2y$10$ddfFumDiAoDhpNj0XYRVHe3CEazScrvDNLqU2X8VwXGCoS6HT4Dt6', 'VientoMadera', '2022-01-10', false);

ALTER SEQUENCE musico_seq RESTART WITH 60;

insert into bus(id, nombre, plazas, precio_km, descuento) values (1, 'Autobús 50 Plazas', 50, 2, 0);
insert into bus(id, nombre, plazas, precio_km, descuento) values (2, 'Autobús 65 Plazas', 65, 2.5, 0);
insert into bus(id, nombre, plazas, precio_km, descuento) values (3, 'Autobús 80 Plazas', 80, 3, 0);
insert into bus(id, nombre, plazas, precio_km, descuento) values (4, 'Autobús 100 Plazas', 100, 3.25, 0);

ALTER SEQUENCE bus_seq RESTART WITH 54;

insert into evento(id, nombre, fecha, hora, duracion, ciudad, kmarecorrer, musicos_necesarios, bus_contratado, dinero_pagado, url_img, bus_id) values (1, 'Concierto Santa Cecilia', '2023-11-18', '18:00', 2, 'Ecija', 0, 65, false, 1000, 'https://pbs.twimg.com/media/F-RPbXyXEAANeVz?format=jpg&name=large', null);
insert into concierto(id, aforo, gratuito, precio) values (1, 100, true, 0);

insert into evento(id, nombre, fecha, hora, duracion, ciudad, kmarecorrer, musicos_necesarios, bus_contratado, dinero_pagado, url_img, bus_id) values (3, 'Concierto Santo Angel', '2024-02-24', '21:15', 2, 'Sevilla', 86.3, 65, true, 3000, 'https://amueci.com/wp-content/uploads/2024/02/cartel1-819x1024.jpg', 2);
insert into concierto(id, aforo, gratuito, precio) values (3, 200, true, 0);

insert into evento(id, nombre, fecha, hora, duracion, ciudad, kmarecorrer, musicos_necesarios, bus_contratado, dinero_pagado, url_img, bus_id) values (4, 'Concierto Marchas Procesionales Huelva', '2025-03-11', '21:00', 2, 'Huelva', 180, 65, true, 2500, 'https://www.artesacro.org/imagenes/IMG-20230309-WA0001.jpg', 2);
insert into concierto(id, aforo, gratuito, precio) values (4, 150, true, 0);

insert into evento(id, nombre, fecha, hora, duracion, ciudad, kmarecorrer, musicos_necesarios, bus_contratado, dinero_pagado, url_img, bus_id) values (5, 'Concierto Santa Cecilia', '2024-11-06', '12:30', 2, 'Ecija', 0, 65, false, 1000, 'https://pbs.twimg.com/media/F-RPbXyXEAANeVz?format=jpg&name=large', null);
insert into concierto(id, aforo, gratuito, precio) values (5, 100, true, 0);

insert into evento(id, nombre, fecha, hora, duracion, ciudad, kmarecorrer, musicos_necesarios, bus_contratado, dinero_pagado, url_img, bus_id) values (6, 'Concierto Santa Cecilia', '2024-11-06', '12:30', 2, 'Ecija', 0, 65, false, 1000, 'https://pbs.twimg.com/media/F-RPbXyXEAANeVz?format=jpg&name=large', null);
insert into concierto(id, aforo, gratuito, precio) values (6, 100, true, 0);

insert into evento(id, nombre, fecha, hora, duracion, ciudad, kmarecorrer, musicos_necesarios, bus_contratado, dinero_pagado, url_img, bus_id) values (7, 'Concierto Santa Cecilia', '2024-11-06', '12:30', 2, 'Ecija', 0, 65, false, 1000, 'https://pbs.twimg.com/media/F-RPbXyXEAANeVz?format=jpg&name=large', null);
insert into concierto(id, aforo, gratuito, precio) values (7, 100, true, 0);


insert into evento(id, nombre, fecha, hora, duracion, ciudad, kmarecorrer, musicos_necesarios, bus_contratado, dinero_pagado, url_img, bus_id) values (2, 'Procesion Cena Huelva', '2024-04-06', '12:30', 8, 'Huelva', 200, 80, true, 10000, 'https://pbs.twimg.com/media/GJbGW2qXoAAXBKZ.jpg', 3);
insert into procesion(id, hermandad, titular, precio_horas_extras) values (2, 'Cena Huelva', 'Rosario del Polvorin', 100);

ALTER SEQUENCE evento_seq RESTART WITH 57;